labstore: notes for nfs-manage
This is terribly broken and this is to prevent
the accidental running of this as a script now which
will not work and could cause weird state issues potentially.

Several issues on this are open but need time and energy.

Bug: T169570
Change-Id: I042672f1cfb281296aa076e7a4e66903326e28b8

diff --git a/modules/role/templates/labs/nfs/nfs-manage.sh.erb b/modules/role/templates/labs/nfs/nfs-manage.sh.erb
--- a/modules/role/templates/labs/nfs/nfs-manage.sh.erb
+++ b/modules/role/templates/labs/nfs/nfs-manage.sh.erb
@@ -12,6 +12,17 @@
 #         floating IP assignment
 # status - Display mount and drbd status
 
+# T169570
+echo "This cannot be run as a script currently"
+echo "These steps can be followed to handle failover manually..."
+echo "Except the 'down' process on the current primary fails at:"
+echo " /usr/local/sbin/nfs-manage-binds"
+echo "A reboot taking the current primary offline and allowing the"
+echo "use of '/sbin/drbdadm primary all --force' on the secondary "
+echo "is the current terrible process in use."
+echo "T169570 and T157478 are the issues to address this."
+exit 1
+
 CMD="$1"
 
 case $CMD in
