labs::lvm:  Fix extend-instance-vol to work on stretch
This is terrible.  The 'lvextend' tool has changed its
return codes betwen Jessie and Trusty, and our old
script errors out on Stretch.  This patch
attempts to detect the version of lvextend and switch
behavior accordingly.

Upstream discussion at
https://bugzilla.redhat.com/show_bug.cgi?id=1365186

Bug: T164534
Change-Id: I6dd879602bd6b927b860ab78dc1d1fa6b7aa4201

diff --git a/modules/labs_lvm/files/extend-instance-vol b/modules/labs_lvm/files/extend-instance-vol
--- a/modules/labs_lvm/files/extend-instance-vol
+++ b/modules/labs_lvm/files/extend-instance-vol
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+
+vercomp () {
+    if [[ $1 == $2 ]]
+    then
+        return 0
+    fi
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+    done
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            return 2
+        fi
+    done
+    return 0
+}
+
 # If we are called with --test as the first parameter, this means that
 # we change nothing on disk, but indicate with an exit status other
 # than 0 that we would have changed anything and with an exit status
@@ -14,6 +46,24 @@ fi
 mount="$1"; shift
 size="$1"; shift
 sopt="-L $size"
+
+# Getting the lvextend version is hellish but we need it because
+#  the return codes changed at version 2.02.141 as per
+#  https://bugzilla.redhat.com/show_bug.cgi?id=1354396
+#
+# If we fail to get the version entirely, we'll assume that it's
+#  post-141.
+lvextendversion=`lvextend --version | head -n 1 | cut -d ' ' -f 9 | cut -d '(' -f 1`
+if [ $? -eq 0 ]; then
+    vercomp $lvextendversion '2.02.141'
+    if [ $? -eq 2 ]; then
+        oldlvextend=true
+    else
+        oldlvextend=false
+    fi
+else
+    oldlvextend=false
+fi
 
 if (/bin/echo "$size"|/bin/grep -q '%'); then
   sopt="-l $size"
@@ -42,16 +92,32 @@ if /sbin/lvextend -t $sopt "$volume" >/dev/null 2>&1; then
   exit
 else
   lvextend_exitcode=$?
-  if [ $lvextend_exitcode -eq 5 ]; then
-    echo "$0: no space left to grow $mount to $size" >&2
-    exit 2
+
+  if $oldlvextend; then
+    if [ $lvextend_exitcode -eq 5 ]; then
+      echo "$0: no space left to grow $mount to $size" >&2
+      exit 2
+    fi
+    # This is the only case when --test should succeed: All the tests
+    # above have passed and lvextend wouldn't do anything because the
+    # partition is already of the requested size.
+    if [ $lvextend_exitcode -eq 3 ] && [ $dryrun -ne 0 ]; then
+      exit 0
+    fi
+  else
+    if [ $lvextend_exitcode -eq 11 ]; then
+      echo "$0: no space left to grow $mount to $size" >&2
+      exit 2
+    fi
+    # Return codes for modern lvextend are unclearly documented.
+    #  '5' is supposed to mean 'logical volume not active'
+    #  but it's what we get in the correct no-op case
+    #  so we'll take it.
+    if [ $lvextend_exitcode -eq 5 ] && [ $dryrun -ne 0 ]; then
+      exit 0
+    fi
   fi
-  # This is the only case when --test should succeed: All the tests
-  # above have passed and lvextend wouldn't do anything because the
-  # partition is already of the requested size.
-  if [ $lvextend_exitcode -eq 3 ] && [ $dryrun -ne 0 ]; then
-    exit 0
-  fi
+
   if [ $dryrun -ne 0 ]; then
     exit 1
   else
