make-instance-vg: check if lvm is present before we start
Bug: T241868
Change-Id: I7c0b47640d28db1dadeb4e15b742227b439ebe9d

diff --git a/modules/labs_lvm/files/make-instance-vg b/modules/labs_lvm/files/make-instance-vg
--- a/modules/labs_lvm/files/make-instance-vg
+++ b/modules/labs_lvm/files/make-instance-vg
@@ -1,5 +1,11 @@
 #! /bin/bash
 
+if ! lvdisplay | grep . >> /dev/null
+then
+    echo "$0: lvm is not active on this host; unable to create a volume."
+    exit 1
+fi
+
 device="$1"
 if ! /sbin/parted -s $device mkpart primary $(
     /sbin/parted -s $device print free |
