ipsec-global: fix bug in non-verbose mode, exit if not root
1. Fix whitespace
2. Exit if script is invoked without root privileges
3. Use [[ ]] for tests
4. Use $() instead of ``
5. Use set -u
6. exit 1 where appropriate
7. In order to provide concise output for execution via Salt, normal output
from the ipsec command is redirected to /dev/null unless the -v flag is
supplied. This patch fixes the following bug (shown via set +x) in
which the stdout redirect is parsed as part of the connection name due to
quotes inserted by expansion of "$@":

$ sudo ipsec-global -b up
+ ipsec stroke up 'curium.eqiad.wmnet-cp3002.esams.wmnet_by_ipv6 >/dev/null'
no config named 'curium.eqiad.wmnet-berkelium.eqiad.wmnet_by_ipv4 >/dev/null'

The fix uses eval, because other syntax I tried all failed. I welcome alternate
solutions. Eval is noted for being a security risk in some situations, but I've
tried to exploit it in this case and I believe it is safe. Exploitation would
require modifying ipsec.conf to supply an invalid connection name such as
"foo;/badscript" as well as modifying this script to remove "set -e". As
modifying either file already requires root, the presence of eval in this
context does not appear to represent a security vulnerability.

If reviewers find this use of eval unacceptable and an alternative fix for the
bug described above isn't found, I'll rewrite this script in perl.

Bug: T88536
Change-Id: I3e20d4f4069ba5a9097993516d2252d1393cb919

diff --git a/modules/strongswan/files/ipsec-global b/modules/strongswan/files/ipsec-global
--- a/modules/strongswan/files/ipsec-global
+++ b/modules/strongswan/files/ipsec-global
@@ -4,9 +4,10 @@
 # jgage@wikimedia.org 2015-03
 
 set -e  # immediately exit if any command has a non-zero exit status
+set -u  # immediately exit when referencing an undefined variable
 
 PATH="/usr/sbin:/usr/bin:/bin"
-CMDNAME=`basename $0`
+CMDNAME=$(basename $0)
 CONF=/etc/ipsec.conf
 
 HELP() {
@@ -20,19 +21,12 @@ HELP() {
     exit
 }
 
-silent() {
-  if [[ $VERBOSE ]] ; then
-    "$@"
-  else
-    "$@ >/dev/null"
-  fi
-}
-
 # Defaults: avoid 'up' and 'status' blocking for multiple minutes as SAs are
 # established, but for 'down' don't return until the action completes
 CMD_UP="up-nb"
 CMD_DOWN="down"
 CMD_STATUS="statusall-nb"
+VERBOSE=""
 
 while getopts "bnvh" FLAG; do
     case $FLAG in
@@ -54,21 +48,39 @@ while getopts "bnvh" FLAG; do
 done
 shift $((OPTIND-1))
 
-if [ ! -r $CONF ] ; then
+silent() {
+    if [[ $VERBOSE = 1 ]] ; then
+        eval "$*"
+    else
+        eval "$* >/dev/null"
+  fi
+}
+
+if [[ ! -r $CONF ]] ; then
     echo "ERROR: Cannot read $CONF"
     echo "For usage info, run: $CMDNAME -h"
-    exit
+    exit 1
 fi
-CONNLIST=`awk '/^conn [^%]/ {print $2}' $CONF`
 
-if [[ -z "$*" ]] ; then
+CONNLIST=$(awk '/^conn [^%]/ {print $2}' $CONF)
+if [[ -z $CONNLIST ]] ; then
+    echo "ERROR: No connections found in $CONF"
+    exit 1
+fi
+
+if [[ -z $* ]] ; then
     echo "ERROR: no arguments"
     echo "For usage info, run: $CMDNAME -h"
-    exit
+    exit 1
+fi
+
+if [[ $EUID -ne 0 ]] ; then
+    echo "ERROR: command must be run as root"
+    exit 1
 fi
 
 case "$1" in
-    up) if [ $CMD_UP = "up-nb" ] ; then
+    up) if [[ $CMD_UP = "up-nb" ]] ; then
             for c in $CONNLIST ; do silent ipsec stroke $CMD_UP $c & done
             echo "Finished launching 'ipsec up' for all connections (async)"
         else
@@ -76,7 +88,7 @@ case "$1" in
             echo "Finished executing 'ipsec up' for all connections (sync)"
         fi
         ;;
-    down) if [ $CMD_DOWN = "down-nb" ] ; then
+    down) if [[ $CMD_DOWN = "down-nb" ]] ; then
             for c in $CONNLIST ; do silent ipsec stroke $CMD_DOWN $c & done
             echo "Finished launching 'ipsec down' for all connections (async)"
         else
@@ -93,5 +105,6 @@ case "$1" in
         ;;
     *)  echo "ERROR: action not recognized"
         echo "For usage info, run: $CMDNAME -h"
+        exit 1
         ;;
 esac
