Tools: Let exec-manage fail if it cannot determine release version
Change-Id: I608023fe993d4dd1e2a8fc741e912496e9b814ab

diff --git a/modules/toollabs/files/exec-manage b/modules/toollabs/files/exec-manage
--- a/modules/toollabs/files/exec-manage
+++ b/modules/toollabs/files/exec-manage
@@ -107,6 +107,10 @@ case $cmd in
             *"-12"*)
                 release="precise"
                 ;;
+            *)
+                echo "Could not determine release version for execution node $exec_host."
+                exit 1
+                ;;
         esac
 
         echo "Submitting a test job to $exec_host"
