Make labs' sql command work with -v and remove cruft
Also applied a consistent code style.

This can be tested by running:
$ sql en -v
which will give a MySQL syntax error with the current
version.

Change-Id: Ic57b5de345073d13185ebf59d4fee7f7a9c17b9f

diff --git a/modules/toollabs/files/sql b/modules/toollabs/files/sql
--- a/modules/toollabs/files/sql
+++ b/modules/toollabs/files/sql
@@ -6,121 +6,112 @@
 verbose=0
 
 function Log {
-if [ $verbose -eq 1 ];then
-	echo "$1"
-fi
+	if [ $verbose -eq 1 ]; then
+		echo "$1"
+	fi
 }
 
-if [ $# -lt 1 ];then
-    echo "Usage: \"sql <database name|wiki name> [-vh]\" type sql --help for more help"
-    exit 0
+if [ $# -lt 1 ]; then
+	echo "Usage: \"sql <database name|wiki name> [-vh]\" type sql --help for more help"
+	exit 0
 fi
 
-if [ "$1" = "-h" ] || [ "$1" == "--help" ];then
-    echo "Usage: sql <database>[_p] [-vh] [command(s)]"
+if [ "$1" = "-h" ] || [ "$1" == "--help" ]; then
+	echo "Usage: sql <database>[_p] [-vh] [command(s)]"
 	echo
 	echo "This tool allows you to easily open a connection to sql database without having to provide the credentials or a database host server"
 	echo "Example: sql frwiki_p"
 	echo
 	echo "Parameters:"
 	echo "  -v: verbose - produce various information about the resolution of db"
+	echo "  -h: help - display this help and exit"
 	echo
 	echo "Report bugs to bugzilla at http://bugzilla.wikimedia.org"
 	exit 0
 fi
 
-for i
-do
-	if [ "$i" = "-v" ] || [ "$i" = "--verbose" ]
-	then
+y=0
+for i; do
+	let y++
+	if [ "$i" == "-v" ] || [ "$i" == "--verbose" ]; then
+		# Pass on everything except the -v/--verbose as that will make mysql fail
+		set -- ${*:1:`expr $y - 1`} ${*:`expr $y + 1`}
 		verbose=1
+		break
 	fi
 done
 
-if [ ! -f ~/replica.my.cnf ] && [ ! -f ~/.my.cnf ]
-then
+if [ ! -f ~/replica.my.cnf ] && [ ! -f ~/.my.cnf ]; then
 	Log "WARNING: There is no configuration file for mysql to use, you will probably be unable to access the database"
 fi
 
-list=/usr/share/dblist
-
 param=""
-# check if the user has a replica file
-if [ -f ~/replica.my.cnf ];then
-    param=" --defaults-file=~/replica.my.cnf"
-else
-    if [ ! -f ~/.my.cnf ];then
-        param=" -p"
-    fi
+# Check if the user has a replica file
+if [ -f ~/replica.my.cnf ]; then
+	param=" --defaults-file=~/replica.my.cnf"
+elif [ ! -f ~/.my.cnf ]; then
+	param=" -p"
 fi
 
 server="enwiki.labsdb"
 db="enwiki_p"
 
 case "$1" in
-    "en" | "enwiki_p")
-        server="enwiki.labsdb"
-        db="enwiki_p"
-    ;;
-    "de" | "dewiki_p")
-        server="dewiki.labsdb"
-        db="dewiki_p"
-    ;;
-    "fr" | "frwiki_p")
-        server="frwiki.labsdb"
-        db="frwiki_p"
-    ;;
-    "cs" | "cswiki_p")
-        server="cswiki.labsdb"
-        db="cswiki_p"
-    ;;
-    "commons")
-        server="commonswiki.labsdb"
-        db="commonswiki_p"
-    ;;
-    "wikidata")
-        server="wikidatawiki.labsdb"
-        db="wikidatawiki_p"
-    ;;
-    "local")
-        server=tools-db
-        db=""
-        if [ -f ~/.my.cnf ];then
-	    param=""
-        fi
-   ;;
-   "commonswiki_p" | "commons")
-       server=commonswiki.labsdb
-       db="commonswiki_p"
-   ;;
-   *)
-	# we don't know what the database is so we check if it exist first
+	 "en" | "enwiki_p")
+		server="enwiki.labsdb"
+		db="enwiki_p"
+	;;
+	"de" | "dewiki_p")
+		server="dewiki.labsdb"
+		db="dewiki_p"
+	;;
+	"fr" | "frwiki_p")
+		server="frwiki.labsdb"
+		db="frwiki_p"
+	;;
+	"cs" | "cswiki_p")
+		server="cswiki.labsdb"
+		db="cswiki_p"
+	;;
+	"commons")
+		server="commonswiki.labsdb"
+		db="commonswiki_p"
+	;;
+	"wikidata")
+		server="wikidatawiki.labsdb"
+		db="wikidatawiki_p"
+	;;
+	"local")
+		server=tools-db
+		db=""
+		if [ -f ~/.my.cnf ]; then
+			param=""
+		fi
+	;;
+	"commonswiki_p" | "commons")
+		server=commonswiki.labsdb
+		db="commonswiki_p"
+	;;
+	*)
 	Log "This database name is not known by sql script, fallback to dblist resolution"
-	# lookup from hosts
-	if [ `echo "$1" | grep -cE '_p$'` -lt 1 ];then
-	     Log "Invalid database name, recursive attempt suffixing _p..."
-	     if ($0 $1_p ${*:2});then
-		     exit 0
-	     fi
-             echo "Make sure to ask for a db in format of <wiki>_p"
-	     exit 1
-	fi
-	db=$1
-	server=`echo "$1" | sed 's/_p//' | sed 's/$/.labsdb/'`
-	if [ `cat /etc/hosts | grep -cE "\s$server"` -gt 0 ]
-	then
+	# Append _p to the database name, if not already present
+	db=`echo $1 | awk '/_p/ { print $1; exit } { print $1"_p" }'`
+
+	server=`echo "$1" | sed 's/_p//'`.labsdb
+	# We don't know the database so we check if it exists first
+	if [ `cat /etc/hosts | grep -cE "\s$server"` -gt 0 ]; then
 		Log "Resolved to $server $db"
 	else
-	        echo "This is unknown db to me, if you don't like that, blame petan on freenode"
-	        exit 1
+		echo "This is unknown db to me, if you don't like that, blame petan on freenode"
+		exit 1
 	fi
-   ;;
+	;;
 esac
 
-shift
+shift # Skip the first param as that's already in $db
 Log "Connecting to $server"
 if [ $# -lt 1 ]; then
-  exec mysql $param -h $server $db "$@"
+	exec mysql $param -h $server $db
 else
-  echo "$@" | mysql $param -h $server $db
+	echo "$@" | exec mysql $param -h $server $db
 fi
