l10nupdate: Reduce code duplication in git clone operations
Change-Id: If86301a13c419a0f67913f57ac061e06c92bf64a

diff --git a/modules/scap/files/l10nupdate-1 b/modules/scap/files/l10nupdate-1
--- a/modules/scap/files/l10nupdate-1
+++ b/modules/scap/files/l10nupdate-1
@@ -46,23 +46,11 @@ echo "Starting l10nupdate at $(date -ud @$BEGAN)."
 echo "Updating git clone ..."
 for path in $GITREPOS
 do
-	if [ -d $GITDIR/$path ]
+	if [ ! -d $GITDIR/$path ]
 	then
-		# Checkout exists, update it
-		if cd $GITDIR/$path && git pull && git submodule update --init
-		then
-			echo "Updated $path"
-		else
-			banglog "LocalisationUpdate failed: git pull of $path failed"
-			echo "Updating $path FAILED."
-			exit 1
-		fi
-	else
-		# Create the checkout's parent directory
-		if mkdir -p `dirname $GITDIR/$path` &&
-			git clone $GITURL/$path $GITDIR/$path &&
-			cd $GITDIR/$path &&
-			git submodule update --init
+		# Create the checkout's parent directory and initial clone
+		if mkdir -p $(dirname $GITDIR/$path) &&
+			git clone $GITURL/$path $GITDIR/$path
 		then
 			echo "Cloned $path"
 		else
@@ -70,6 +58,18 @@ do
 			echo "Cloning $path FAILED."
 			exit 1
 		fi
+	fi
+
+	cd $GITDIR/$path
+	# Update checkout of repo
+	if git pull &&
+		git submodule update --init --recursive
+	then
+		echo "Updated $path"
+	else
+		banglog "LocalisationUpdate failed: git pull of $path failed"
+		echo "Updating $path FAILED."
+		exit 1
 	fi
 done
 echo "git clone updated."
