Handle invalid DB name in 'sql' shell script
When the 'sql' shell script is used with an invalid DB name,
the eval.php calls used to look up DB host/password fatal out,
the variables will contain the error message, mysql gets
confused and dumps its help text (which is several pages).

This is confusing at best, and dangerous when the command is scripted.
The patch outputs an intelligible error message instead, includes the DB name,
and sends it to stderr so it can be filtered out from scripts.

Change-Id: I61467d3520bca3e62a391e97efc9ec01a9f521b5

diff --git a/modules/scap/files/sql b/modules/scap/files/sql
--- a/modules/scap/files/sql
+++ b/modules/scap/files/sql
@@ -44,5 +44,11 @@ fi
 host=`echo $lbcode $hostcode | /usr/local/bin/mwscript eval.php --wiki="$lookupdb"`
 pass=`echo 'echo \$wgDBadminpassword;' | /usr/local/bin/mwscript eval.php --wiki="$lookupdb"`
 
+if [ $? -ne 0 ]; then
+    # PHP error, probably an invalid DB code
+    echo "Error looking up DB \"$db\"" 1>&2
+    exit 1
+fi
+
 # Execute mysql.
 exec mysql -u wikiadmin -p$pass -h $host -D $db "$@"
