Split sql to sql and sqlhost
Bug: T141255
Change-Id: I8b1ff1acafdd51722ce5259b40710c9c363ddfaf

diff --git a/modules/scap/files/sql b/modules/scap/files/sql
--- a/modules/scap/files/sql
+++ b/modules/scap/files/sql
@@ -14,41 +14,24 @@ if [ -z "$db" ] || [ "$db" = "--help" ]; then
     echo 'Usage: sql [--write] <dbname> [mysqloptions]'
     exit 0
 elif [ "$db" = "--write" ]; then
-    hostcode="echo \$lb->getServerName(0);"
-
     # Database will be the next parameter
     db=$1
     shift
-else
-    hostcode="echo \$lb->getServerName(\$lb->getReaderIndex());"
-fi
 
-# Look up MySQL host to connect to.  For centralauth the host cannot
-# be determined this way, so we need to use fawiki instead as it is
-# located on the same server in both production and labs.
-# wikishared is hosted on x1 (i.e. without any local wikis), just use
-# meta to lookup the password.
-if [ "$db" = "centralauth" ]; then
-    lookupdb="fawiki"
-elif [ "$db" = "wikishared" ]; then
-    lookupdb="metawiki"
+    hostpass=`./sqlhost --write $db`
 else
-    lookupdb="$db"
+    hostpass=`./sqlhost $db`
 fi
-
-if [ "$db" = "wikishared" ]; then
-    lbcode="\$lb = wfGetLBFactory()->getExternalLB('extension1');"
-else
-    lbcode="\$lb = wfGetLB();"
-fi
-host=`echo $lbcode $hostcode | /usr/local/bin/mwscript eval.php --wiki="$lookupdb"`
-pass=`echo 'echo \$wgDBadminpassword;' | /usr/local/bin/mwscript eval.php --wiki="$lookupdb"`
 
 if [ $? -ne 0 ]; then
     # PHP error, probably an invalid DB code
-    echo "Error looking up DB \"$db\"" 1>&2
-    exit 1
+    echo "sql: Error looking up DB \"$db\"" 1>&2
+    exit $?
 fi
+
+hostpass=($hostpass)
+host=${hostpass[0]}
+pass=${hostpass[1]}
 
 # Execute mysql.
 exec mysql -u wikiadmin -p$pass -h $host -D $db "$@"
