toolforge: exec-manage: fix 'list' option
Previous to this patch, the 'list' option required a parameter for no reason.
Make the parameter checks only for the options that really require it.

While at it, update help invocation and usage message.

Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>
Change-Id: Ib921b2b71cc15fd5c2b98e90c500084868cc3d58

diff --git a/modules/profile/files/toolforge/exec-manage b/modules/profile/files/toolforge/exec-manage
--- a/modules/profile/files/toolforge/exec-manage
+++ b/modules/profile/files/toolforge/exec-manage
@@ -10,26 +10,25 @@ function usage {
         echo -e "Usage:\n"
         echo "exec-manage [status|depool|repool] exec_host_name"
         echo "exec-manage [list]"
+        echo "exec-manage [help|--help|-h]"
         echo ""
         echo "Example: exec-manage status tools-exec1001.tools.eqiad.wmflabs"
 }
 
-if [[ ! "$1" || "$1" == '-h' ]]; then
-    usage
-    exit 0
-fi
-
-if [ "$#" -ne 2 ]; then
-    echo "Wrong number of parameters"
-    usage
-    exit 1
-fi
+function check_missing_param {
+    if [ "$1" != "2" ] ; then
+        echo -e "ERROR: wrong number of parameters\n" >&2
+        usage
+        exit 1
+    fi
+}
 
 cmd=$1
 exec_host=$2
 
 case $cmd in
     depool)
+        check_missing_param $#
 
         # Collect the list of jobs running on this host, and convert them
         # to pipe separated string, this is useful to show status of these jobs
@@ -69,6 +68,7 @@ case $cmd in
         ;;
 
     repool)
+        check_missing_param $#
 
         # Enables all queues on this host
         /usr/bin/qmod -e "*@$exec_host"
@@ -77,6 +77,7 @@ case $cmd in
         ;&
 
     status)
+        check_missing_param $#
 
         # List count of running jobs on host
         echo "Count of jobs running on host $exec_host : "
@@ -96,6 +97,15 @@ case $cmd in
 
         ;;
 
+    help)
+        usage
+        ;;
+    "--help")
+        usage
+        ;;
+    "-h")
+        usage
+        ;;
     *)
         usage
 
