Update labs-private as well as production puppet repo.
Bug: T92756

Change-Id: I51c7aafde78b98106d55f05a48555c208de2f065

diff --git a/modules/puppetmaster/templates/git-sync-upstream.erb b/modules/puppetmaster/templates/git-sync-upstream.erb
--- a/modules/puppetmaster/templates/git-sync-upstream.erb
+++ b/modules/puppetmaster/templates/git-sync-upstream.erb
@@ -12,6 +12,7 @@ set -e
 echo "--- $0 $(date +%Y-%m-%dT%H:%M:%S)"
 
 REPO='<%= @repo_path %>'
+PRIVATEREPO='<%= @private_repo_path %>'
 TRACK_BRANCH=production
 REBASE_OPTS=(
     '--preserve-merges'
@@ -60,3 +61,52 @@ STATS_PREFIX="`cat /etc/wmflabs-project`.`cat /etc/wmflabs-instancename`"
 CHERRY_PICKED_COUNT=`git log --pretty=oneline --abbrev-commit origin/HEAD..HEAD | wc -l`
 echo -n "$STATS_PREFIX.puppetmaster.cherrypicked_commits:$CHERRY_PICKED_COUNT|g" |
     nc -w 1 -u <%= @statsd_host %> 8125
+
+
+if [ -z "$PRIVATE_REPO" ]; then
+    exit 0
+fi
+
+# Now, the labs-private repo
+cd ${PRIVATE_REPO}
+
+DIFF=`git diff`
+if [ -n "$DIFF" ]; then
+    echo "Local diffs detected.  Commit your changes!"
+    exit 2
+fi
+
+# Fetch new changes from origin
+
+GIT_SSH=/var/lib/git/ssh
+git fetch --verbose origin
+
+# Rebase locally commited changes on top of tracked origin branch
+git rebase "${REBASE_OPTS[@]}" origin/${TRACK_BRANCH}
+
+if [[ $? -ne 0 ]]; then
+    echo "Rebase failed! See error messages above." 1>&2
+    echo "Reverting rebase attempt" 1>&2
+    git rebase --abort
+    exit 2
+fi
+
+# Ensure that submodule changes are applied to the local checkout
+git submodule update --init --recursive
+
+# Tag the local repo state for rollback and troubleshooting
+TAG="beta-$(date +%Y%m%dT%H%M)"
+git tag "$TAG"
+echo "Tagged as: ${TAG}"
+
+# Display local commits
+echo "Local hacks:"
+git log --color --pretty=oneline --abbrev-commit origin/HEAD..HEAD |
+sed 's/^/  /'
+
+# Send stats on how many cherry-picked commits there are to statsd
+STATS_PREFIX="`cat /etc/wmflabs-project`.`cat /etc/wmflabs-instancename`"
+CHERRY_PICKED_COUNT=`git log --pretty=oneline --abbrev-commit origin/HEAD..HEAD | wc -l`
+echo -n "$STATS_PREFIX.puppetmaster.cherrypicked_commits:$CHERRY_PICKED_COUNT|g" |
+    nc -w 1 -u <%= @statsd_host %> 8125
+
