Revert "Revert "puppetmaster: clearer edit message when you can't rewrite history""
This reverts commit f9e9a5d3e19270f9a1c90a4390dadc0738676cf2.

Reason for revert: Changing to #!/bin/bash and then testing it.

Change-Id: I92e9a05f32f9fb85dbe305b48c3314bdbc1a3760

diff --git a/modules/puppetmaster/templates/git-master-postcommit.erb b/modules/puppetmaster/templates/git-master-postcommit.erb
--- a/modules/puppetmaster/templates/git-master-postcommit.erb
+++ b/modules/puppetmaster/templates/git-master-postcommit.erb
@@ -1,7 +1,15 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 set -u
+
+trap 'reporterr' ERR
+
+reporterr() {
+  echo "⚠️  Something went wrong!  Maybe you attempted to rewrite history?"
+  echo "You can't rebase or commit --amend in this repo.  If you tried that,"
+  echo "perform the repair steps under = What NOT to do = in the README."
+}
 
 # Refresh the local copy
 su -c 'cd /var/lib/git/operations/private && git pull' gitpuppet
