puppetmaster: Make puppet-merge a template
And add the $servers variable so we can use it to generate the required
puppet merge commands on the backends

Change-Id: Ia1dbb789a426ac335e64b73af4d2c40a77824bea

diff --git a/modules/puppetmaster/templates/puppet-merge.erb b/modules/puppetmaster/templates/puppet-merge.erb
--- a/modules/puppetmaster/templates/puppet-merge.erb
+++ b/modules/puppetmaster/templates/puppet-merge.erb
@@ -7,6 +7,7 @@ set -e
 
 # Colorized output helpers
 RED=$(tput bold; tput setaf 1)
+GREEN=$(tput bold; tput setaf 2)
 MAGENTA=$(tput bold; tput setaf 9)
 RESET=$(tput sgr0)
 FORCE=0
@@ -150,3 +151,19 @@ else
     cd -
     exit 1
 fi
+
+<%- if @servers.has_key?(@fqdn) -%>
+# Note: The "true" command is passed on purpose to show that the command passed
+# to the SSH sessions is irrelevant. It's the SSH forced command trick on the
+# worker end that does the actual work. Note that the $sha1 however is important
+  <%- @servers.each do |frontend, workers| -%>
+    <%- workers.map{ |w| w['workerhash']}.select{|name| name != @fqdn}.each do |worker| -%>
+ssh -t -t <%= worker -%> "true ${sha1}" 2>&1 | tee -a /var/log/puppet-post-merge.log
+if [ $? -eq 0 ]; then
+    echo "${GREEN}OK${RESET}: puppet-merge on <%= worker %> succeded"
+else
+    echo "${RED}ERROR${RESET}: puppet-merge on <%= worker %> failed"
+fi
+    <%- end -%>
+  <%- end -%>
+<%- end -%>
