puppet-merge: fix lock detection
Change-Id: I40f9c32bfc247fca6031b9887cce6b49c1c0d8da

diff --git a/modules/puppetmaster/templates/puppet-merge.erb b/modules/puppetmaster/templates/puppet-merge.erb
--- a/modules/puppetmaster/templates/puppet-merge.erb
+++ b/modules/puppetmaster/templates/puppet-merge.erb
@@ -35,7 +35,7 @@ lock() {
       else
         PSTREE="could not determine lock holder"
       fi
-      die "failed to lock, another puppet-merge running on this host?\n${PSTREE}"
+      printf "E: failed to lock, another puppet-merge running on this host?\n%s" "${PSTREE}" >&2
   fi
 }
 
