puppet_compiler: update compiler-update-fact
The current version of the scripts exports the set of facts from the
puppet master for each compiler.  This operation is quite expensive,
this CR updates the script so we only preform the fact export once,
copy it to all copies and then clean up

If CR is accepted update the wikitech article
 https://wikitech.wikimedia.org/wiki/Nova_Resource:Puppet-diffs

Change-Id: I18ea4766e1871e5a3476701c35098a3df0a9ad9f

diff --git a/modules/puppet_compiler/files/compiler-update-facts b/modules/puppet_compiler/files/compiler-update-facts
--- a/modules/puppet_compiler/files/compiler-update-facts
+++ b/modules/puppet_compiler/files/compiler-update-facts
@@ -5,10 +5,9 @@
 # locally from a computer that has root access to all puppet masters and the
 # puppet compiler machine.
 
-set -e
-set -u
+set -eu
 
-COMPILER=${PUPPET_COMPILER:-compiler1001.puppet-diffs.eqiad.wmflabs}
+COMPILERS=${PUPPET_COMPILERS:-compiler1001.puppet-diffs.eqiad.wmflabs compiler1002.puppet-diffs.eqiad.wmflabs compiler1003.puppet-diffs.eqiad.wmflabs}
 RUBY_SCRIPT=$(cat <<'RUBY_SCRIPT'
 require 'safe_yaml'
 SafeYAML::OPTIONS[:default_mode] = :safe
@@ -18,14 +17,18 @@ RUBY_SCRIPT
 )
 
 
-ssh "$COMPILER" 'sudo rm -rf /tmp/facts; sudo mkdir -p /tmp/facts'
 # Gather all the facts from one of the masters.
 master=${PUPPET_MASTER:-$(ruby -e "${RUBY_SCRIPT}" < hieradata/common/puppetmaster.yaml)}
-echo -e "\n### Syncing facts from $master"
-ssh "$master" 'sudo /usr/local/bin/puppet-facts-export 1>/dev/null'
+printf "\\n### Syncing facts from %s\\n" "${master}"
+ssh "$master" 'sudo /usr/local/bin/puppet-facts-export &>/dev/null'
 # tunnel via your localhost without ever the file touching the disk
-ssh "$master" cat /tmp/puppet-facts-export.tar.xz | ssh "$COMPILER" 'cat > puppet-facts-export.tar.xz'
+for COMPILER in $COMPILERS
+do
+  printf "copy facts to: %s\\n" "${COMPILER}"
+  scp -3 "$master":/tmp/puppet-facts-export.tar.xz "${COMPILER}":puppet-facts-export.tar.xz
+  ssh "$COMPILER" 'sudo rm -rf /tmp/facts; sudo mkdir -p /tmp/facts'
+  ssh "$COMPILER" 'sudo tar Jxf puppet-facts-export.tar.xz --directory /tmp/facts && sudo chown -R jenkins-deploy:wikidev /tmp/facts/yaml'
+  # Finally, copy all the facts to destination and cleanup
+  ssh "$COMPILER" "sudo rsync --delete -au /tmp/facts/yaml/ /var/lib/catalog-differ/puppet/yaml/${master} && sudo rm -rf /tmp/facts"
+done
 ssh "$master" 'sudo rm /tmp/puppet-facts-export.tar.xz'
-ssh "$COMPILER" 'sudo tar Jxf puppet-facts-export.tar.xz --directory /tmp/facts && sudo chown -R jenkins-deploy:wikidev /tmp/facts/yaml'
-# Finally, copy all the facts to destination and cleanup
-ssh "$COMPILER" "sudo rsync --delete -au /tmp/facts/yaml/ /var/lib/catalog-differ/puppet/yaml/$master && sudo rm -rf /tmp/facts"
