Maps - enable tileratorui notification of new expier files
After running update of OSM data, notify tileratorui of the new expire files.

Tileratorui always returns an empty response (which is invalid). Ignore this
issue until this is fixed.

Bug: T139451
Change-Id: I94e03f8dc2224ceacf2cac2b22d5f41da8b793ba

diff --git a/modules/tilerator/templates/notify-tilerator.erb b/modules/tilerator/templates/notify-tilerator.erb
--- a/modules/tilerator/templates/notify-tilerator.erb
+++ b/modules/tilerator/templates/notify-tilerator.erb
@@ -1,3 +1,16 @@
 #!/bin/bash
 
 /usr/bin/curl -XPOST <%= @notify_url %>
+
+notification_code=$?
+
+if [ $notification_code -eq 52 ] ; then
+    # tileratorui returns an invalid empty response, ignoring it until it is
+    # fixed (T139451)
+    exit 0
+fi
+
+if [ $notification_code -ne 0 ] ; then
+    echo "Error while notifying tileratorui"
+    exit $notification_code
+fi
