Notify TileratorUI on new expiry files
When expiry file has been generated, let Tiletator know
about it. Tilerator will process all files matching the pattern
since the last run (as stored in the state file)

Bug: T108459
Change-Id: If453b48296f01f631ffc4223d56611ed6a16067a

diff --git a/modules/osm/templates/replicate-osm.erb b/modules/osm/templates/replicate-osm.erb
--- a/modules/osm/templates/replicate-osm.erb
+++ b/modules/osm/templates/replicate-osm.erb
@@ -26,3 +26,19 @@ export JAVACMD_OPTIONS="\
       --username osmupdater \
       --database gis \
       --append $EXTRA_PARAMS -
+
+if [ $? -ne 0 ] ; then
+  echo "Error while replicating OSM data"
+  exit -1
+fi
+
+<% if @postreplicate_command %>
+<%= @postreplicate_command %>
+
+if [ $? -ne 0 ] ; then
+    echo "Error while running post-replicate command"
+    exit -1
+fi
+<% end %>
+
+
