sslcert::ocsp: Don't break everything in absence of any config
If you had no config for these you'd get:
usage: update-ocsp [-h] [--config FILE]
update-ocsp: error: argument --config/-f: /etc/update-ocsp.d/*.conf does not exist
OCSP update failed for /etc/update-ocsp.d/*.conf

This blocks e.g. nginx from starting.

Change-Id: Id2e5649eadef4589c7a474cb40a38fe17f027e1f

diff --git a/modules/sslcert/files/update-ocsp-all b/modules/sslcert/files/update-ocsp-all
--- a/modules/sslcert/files/update-ocsp-all
+++ b/modules/sslcert/files/update-ocsp-all
@@ -2,13 +2,15 @@
 
 some_failed=0
 
-for config in /etc/update-ocsp.d/*.conf; do
-    /usr/local/sbin/update-ocsp --config $config
-    if [ $? -ne 0 ]; then
-        echo "OCSP update failed for $config"
-        some_failed=1
-    fi
-done
+if ls /etc/update-ocsp.d/*.conf >/dev/null; then
+    for config in /etc/update-ocsp.d/*.conf; do
+        /usr/local/sbin/update-ocsp --config $config
+        if [ $? -ne 0 ]; then
+            echo "OCSP update failed for $config"
+            some_failed=1
+        fi
+    done
+fi
 
 run-parts /etc/update-ocsp.d/hooks
 
