Add airflow instance profile script, use it from scheduler and webserver
We need a way to set arbitrary environment variables for use
by the airflow webserver, scheduler and the CLI. A commmon
profile script for this is helpful.  Now, the instance's
airflow CLI wrapper sources its profile, and the webserver
and scheduler systemd units launch via the CLI wrapper.

This will also make it easier to debug things via python
CLI, as we can manually source the profile script too.

Add $environment_extra for setting arbitrary env vars.

Also set AIRFLOW_INSTNANCE_NAME env var always, so that
dag config code can be aware of where it is being run.

Bug: T295201
Change-Id: I214084d43f160eb0289dc3ca97ca2e29215f63f9

diff --git a/modules/airflow/templates/airflow.sh.erb b/modules/airflow/templates/airflow.sh.erb
--- a/modules/airflow/templates/airflow.sh.erb
+++ b/modules/airflow/templates/airflow.sh.erb
@@ -3,15 +3,20 @@
 # NOTE: This file is managed by Puppet.
 
 #
-# Wrapper script to invoke airflow from the correct context
+# Wrapper script to invoke airflow CLI from the correct context
 #
-
-AIRFLOW_PREFIX=<%= @airflow_prefix %>
-export AIRFLOW_HOME=<%= @airflow_home %>
 
 if [ "$(whoami)" != "<%= @service_user %>" ]; then
     echo ERROR: $0 must be run as user: <%= @service_user %>
     exit 1
 fi
 
-${AIRFLOW_PREFIX}/bin/airflow $@
+# If an airflow profile.sh exists for this airflow instance, source it now.
+test -f <%= @profile_file %> && source <%= $profile_file %>
+
+if [ -z "${AIRFLOW_HOME}" ]; then
+    echo "ERROR: AIRFLOW_HOME is not set."
+    exit 1
+fi
+
+<%= @airflow_prefix %>/bin/airflow $@
