Added a bunch of arg and error checking.
This way we should be able to call this script from elsewhere and
actually get a reliable exit code.

Change-Id: I75ab6667fc72733616bd48600ace45ed1121cfcd

diff --git a/files/openstack/havana/virtscripts/dc-migrate b/files/openstack/havana/virtscripts/dc-migrate
--- a/files/openstack/havana/virtscripts/dc-migrate
+++ b/files/openstack/havana/virtscripts/dc-migrate
@@ -12,6 +12,10 @@ then
 fi
 INSTANCENAME=$1
 PROJECT=$2
+if [ -z "$INSTANCENAME" -o -z "$PROJECT" ]; then
+	echo "Usage:  $0 <instance to migrate> <instance project>"
+	exit 1
+fi
 FROMREGION='pmtpa'
 TOREGION='eqiad'
 FROMAUTH="http://virt0.wikimedia.org:35357/v2.0"
@@ -25,15 +29,28 @@ if [ -n "$TOINSTANCE" ]; then
 fi
 echo "(That error was a good thing.)"
 echo ""
+FROMINSTANCENAME=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep 'OS-EXT-SRV-ATTR:instance_name' | awk '{ print $4 }'`
+if [ -z "$FROMINSTANCENAME" ]; then
+	echo "ERROR: ${INSTANCENAME} cannot be found in project ${PROJECT}"
+	exit 1
+fi
+FROMINSTANCESTATUS=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep ' status ' | awk '{ print $4 }'`
+if [ "$FROMINSTANCESTATUS" != 'ACTIVE' ]; then
+	echo "ERROR: ${INSTANCENAME} must be ACTIVE before we can migrate it."
+	exit 1
+fi
 FROMIMAGE=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep ' image ' | awk '{gsub ( "[()]","" ) ; print $(NF-1) }'`
 FROMFLAVOR=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep ' flavor ' | awk '{gsub ( "[()]","" ) ; print $5 }'`
 FROMSECURITYRAW=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep ' security_groups ' | awk  -F "|" '{ print $3 }'`
 FROMSECURITY=`python -c "print ','.join([o['name'] for o in ${FROMSECURITYRAW}])"`
 FROMHOST=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep 'OS-EXT-SRV-ATTR:host' | awk '{ print $4 }'`
-FROMINSTANCENAME=`OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${FROMAUTH} nova --os-region ${FROMREGION} show ${INSTANCENAME} | grep 'OS-EXT-SRV-ATTR:instance_name' | awk '{ print $4 }'`
 FROMINSTANCE=$FROMINSTANCENAME
 echo "Creating initial image in $TOREGION"
-cd /srv/org/wikimedia/controller/wikis/w && php ./extensions/OpenStackManager/maintenance/createInstance.php --image ${FROMIMAGE} --flavor ${FROMFLAVOR} --instance ${INSTANCENAME} --project ${PROJECT} --region ${TOREGION} --securitygroups ${FROMSECURITY} --copypuppet ${FROMINSTANCE} --copypuppetregion ${FROMREGION}
+CREATED=`cd /srv/org/wikimedia/controller/wikis/w && php ./extensions/OpenStackManager/maintenance/createInstance.php --image ${FROMIMAGE} --flavor ${FROMFLAVOR} --instance ${INSTANCENAME} --project ${PROJECT} --region ${TOREGION} --securitygroups ${FROMSECURITY} --copypuppet ${FROMINSTANCE} --copypuppetregion ${FROMREGION}`
+if [ "$CREATED" != "created instance." ]; then
+	echo "ERROR: Failed to create new instance in ${TOREGION}"
+	exit 1
+fi
 echo "The new instance is building.  Waiting for it to be assigned a host..."
 TOHOST=''
 while [ -z $TOHOST ]; do
@@ -70,10 +87,15 @@ echo "Rsyncing instance from $FROMHOST to $TOHOST"
 echo ""
 # This one is right, but requires known_hosts to be set up properly:
 ssh -A $FROMHOST.$FROMREGION.wmnet "rsync -S -av /var/lib/nova/instances/${FROMINSTANCE}/* ${TOHOST}.${TOREGION}.wmnet:/var/lib/nova/instances/${TOINSTANCE}"
+if [ "$?" != "0" ]
+then
+	echo "Rsync to new instance failed."
+	exit 1
+fi
 # This is dumb but will work:
 #rsync -S -av ${FROMHOST}.${FROMREGION}.wmnet:/var/lib/nova/instances/${FROMINSTANCE} /tmp/
 #rsync -S -av /tmp/${FROMINSTANCE}/* ${TOHOST}.${TOREGION}.wmnet:/var/lib/nova/instances/${TOINSTANCE}
-rm -r /tmp/${FROMINSTANCE}
+#rm -r /tmp/${FROMINSTANCE}
 echo ""
 echo ""
 echo ""
@@ -83,3 +105,4 @@ echo ""
 echo "Rebooting the instance"
 echo ""
 OS_TENANT_NAME=${PROJECT} OS_AUTH_URL=${TOAUTH} nova --os-region ${TOREGION} reboot ${INSTANCENAME}
+exit 0
