P:dns::auth: skipping running authdns-update on host if not pooled
This commit is based on a question from Riccardo and a suggestion from
him: if a given DNS host is not pooled in confd, we are still running
authdns-local-update on it if authdns-update was run from that host.
That might not be the best behaviour however as most people SSH to the
DNS host in their backlog or from their muscle memory (most of the time
dns1004 or some host in eqiad) and if dns1004 was depooled in confd, we
should not be pulling in updates to it.

This commit checks if the host is in the pooled list and if yes, it will
run authdns-update on itself. If not, it will skip it over.

Bug: T347054
Hosts: dns6001.wikimedia.org, dns1004.wikimedia.org
Change-Id: I64ad7e02c7ab8c138d6183f7006a14dd6af6e361

diff --git a/modules/profile/files/dns/auth/authdns-update b/modules/profile/files/dns/auth/authdns-update
--- a/modules/profile/files/dns/auth/authdns-update
+++ b/modules/profile/files/dns/auth/authdns-update
@@ -32,12 +32,27 @@ while [ -n "$1" ]; do
     shift
 done
 
-# update the local instance first -- this may call a review interactively
-echo "Updating $FQDN (self)..."
-# this might seem silly at first, ssh'ing to self; however, this is a paranoid
-# step to ensure that we're running in the exact same way as the slaves and if
-# it fails, it fail for all of them, instead of having a split-brain.
-ssh $SSH_OPTIONS $FQDN authdns-local-update
+# Only update the current host if it is pooled and in $NAMESERVERS. Otherwise,
+# we don't allow running authdns-update as the human review part of the process
+# fails as all the other hosts are updated non-interactively.
+for host in $NAMESERVERS; do
+    if [ "$FQDN" = "$host" ]; then
+        host_pooled=true
+        break
+    fi
+done
+
+if [ "$host_pooled" = true ] ; then
+    # update the local instance first -- this may call a review interactively
+    echo "Updating $FQDN (self)..."
+    # this might seem silly at first, ssh'ing to self; however, this is a paranoid
+    # step to ensure that we're running in the exact same way as the slaves and if
+    # it fails, it fail for all of them, instead of having a split-brain.
+    ssh $SSH_OPTIONS $FQDN authdns-local-update
+else
+    echo "Unable to run authdns-update from this host: $FQDN is not pooled. Please pick another host!"
+    exit 1
+fi
 
 OTHERS_OPT=""
 for other in $NAMESERVERS; do
