P:dns:auth: exit on non-zero code from clush
clush failing for any reason indicates that we should not proceed to
show that authdns-update was successful. So show that it was not and
then error out.

Change-Id: Ibbbe8013a57c67d7260355e60c1ced11b0d1728b

diff --git a/modules/profile/files/dns/auth/authdns-update b/modules/profile/files/dns/auth/authdns-update
--- a/modules/profile/files/dns/auth/authdns-update
+++ b/modules/profile/files/dns/auth/authdns-update
@@ -68,6 +68,11 @@ for other in $NAMESERVERS; do
     OTHERS_OPT="${OTHERS_OPT} -w ${other}"
 done
 
-clush $CLUSH_OPTIONS -o "${SSH_OPTIONS}" $OTHERS_OPT authdns-local-update $FQDN
+if clush $CLUSH_OPTIONS -o "${SSH_OPTIONS}" $OTHERS_OPT authdns-local-update $FQDN; then
+    echo ""; echo "clush ran successfully on all nodes"
+else
+    echo ""; echo "Error: authdns-update failed as clush returned a non-zero exit code; check the output above!"
+    exit 1
+fi
 
 echo ""; echo "OK - authdns-update successful on all nodes!"
