last-puppet-run: don't crash if puppet has not run yet
Instead now it will print a message too saying so.

=== Test Plan
Ran it locally without any puppet state files and saw that it printed
the message (bold included, note the [1m/[0m strings):

https://phabricator.wikimedia.org/P14129

Then created the follwing:
* the last_run_report.yaml file:

```
$ echo "configuration_version: 1234567890" > /var/lib/puppet/state/last_run_report.yaml
```

* The stat file:

```
$ touch /var/lib/puppet/state/classes.txt
```

And ran it again to see the ok message:

```
$ ./modules/base/files/puppet/97-last-puppet-run
The last Puppet run was at Mon 16 Nov 2020 04:30:38 PM CET (0 minutes ago).
Last puppet commit: 1234567890
```

Then had to change the report file to something that had not been
modified in a while (/etc/passwd) to see the 'last run too old message'
with the bold too (note the [1m/[0m strings):

https://phabricator.wikimedia.org/P14131

Change-Id: I178695bb9fff3b103e5ec3f1a8a78a49e62dd0c7
Signed-off-by: David Caro <dcaro@wikimedia.org>

diff --git a/modules/base/files/puppet/97-last-puppet-run b/modules/base/files/puppet/97-last-puppet-run
--- a/modules/base/files/puppet/97-last-puppet-run
+++ b/modules/base/files/puppet/97-last-puppet-run
@@ -1,20 +1,27 @@
 #!/bin/sh
 # Script that reports when Puppet last ran, in bold if more than an hour ago.
+# Also mentions if it has never run yet
 
 set -e
 
+PUPPET_STATE_DIR=/var/lib/puppet/state
+PUPPET_LAST_RUN_PATH="${PUPPET_STATE_DIR}/last_run_report.yaml"
 PATH=/bin:/usr/bin:/usr/local/bin
 LANG=C
-CONFIG_VERSION=$(grep -m1 -A1 '^configuration_version:' /var/lib/puppet/state/last_run_report.yaml| ruby -ryaml -e 'puts YAML.load(STDIN.read)["configuration_version"]')
-TSLASTPUPPETRUN=$(stat -c %Z /var/lib/puppet/state/classes.txt)
-NOW=$(date +%s)
-DELTAMIN=$(((NOW-TSLASTPUPPETRUN)/60))
-BOLD="\\033[1m"
-NORM="\\033[0m"
-LAST_RUN=$(date -d @"${TSLASTPUPPETRUN}")
-if [ $DELTAMIN -gt 60 ]; then
-	MSG="${BOLD}($DELTAMIN minutes ago)${NORM}. $(puppet-enabled || true)"
+BOLD='\033[1m'
+NORM='\033[0m'
+if [ -f "$PUPPET_LAST_RUN_PATH" ]; then
+    CONFIG_VERSION=$(grep -m1 -A1 '^configuration_version:' "$PUPPET_LAST_RUN_PATH"| ruby -ryaml -e 'puts YAML.load(STDIN.read)["configuration_version"]')
+    TSLASTPUPPETRUN=$(stat -c %Z "${PUPPET_STATE_DIR}/classes.txt")
+    NOW=$(date +%s)
+    DELTAMIN=$(((NOW-TSLASTPUPPETRUN)/60))
+    LAST_RUN=$(date -d @"${TSLASTPUPPETRUN}")
+    if [ $DELTAMIN -gt 60 ]; then
+        MSG="${BOLD}($DELTAMIN minutes ago)${NORM}. $(puppet-enabled || true)"
+    else
+        MSG="($DELTAMIN minutes ago). $(puppet-enabled || true)"
+    fi
+    printf "The last Puppet run was at %s %b\\nLast puppet commit: %s\\n" "${LAST_RUN}" "${MSG}" "${CONFIG_VERSION}"
 else
-	MSG="($DELTAMIN minutes ago). $(puppet-enabled || true)"
+    printf "Puppet %bdoes not seem to have run in this machine%b. Unable to find '%s'.\\n" "$BOLD" "$NORM" "$PUPPET_LAST_RUN_PATH"
 fi
-printf "The last Puppet run was at %s %b\\nLast puppet commit: %s\\n" "${LAST_RUN}" "${MSG}" "${CONFIG_VERSION}"
