run-puppet-agent: some tweaks
* Add proper option handling including long options
* Add option to enable puppet if it was disabled
* Raised default number of attempts to 12, added an option to customize
  the number

Change-Id: I12d00dbb83fc662149cab161ae8050a1d37a1b82

diff --git a/modules/base/files/puppet/run-puppet-agent b/modules/base/files/puppet/run-puppet-agent
--- a/modules/base/files/puppet/run-puppet-agent
+++ b/modules/base/files/puppet/run-puppet-agent
@@ -1,21 +1,77 @@
 #!/bin/bash
-OPTIND=1
 verbose_opts="--verbose"
+force=""
+attempts=12
+enable=""
 
-while getopts "q" opt; do
-    case "$opt" in
-        q)  verbose_opts=""
+show_help() {
+    cat << EOF
+Usage: ${0##*/} [-q] [-a ATTEMPTS] [-e [MSG]|-f]
+Will execute a puppet agent run reliably, waiting for any preceding puppet runs
+to complete before starting. This should allow to ensure a coordinated puppet
+run after a change is effective everywhere.
+
+Options:
+    -q --quiet      Will make the puppet run quiet and not output any verbose
+                    difference.
+    -e --enable MSG Will enable puppet if $MSG is present
+    -f --force      Will forcibly enable puppet if it's not enabled.
+    -a --attempts N When waiting for a preceding puppet run, wait N*10 seconds
+                    before giving up.
+EOF
+}
+
+
+while :; do
+    case "$1" in
+        -q|--quiet)  verbose_opts=""
+            ;;
+        -f|--force)
+            force=1
+            ;;
+        -a|--attempts)
+            if [ -n "$2" ]; then
+                attempts=$2
+                shift
+            else
+                show_help
+                exit 1
+            fi
+            ;;
+        -e|--enable)
+            if [ -n "$2" ]; then
+                enable=$2
+                shift
+            else
+                show_help
+                exit 1
+            fi
+            ;;
+        -h|--help)
+            show_help
+            exit 0
+            ;;
+        -*)
+            printf "Unkown option: %s" "$1" >&2
+            show_help
+            exit 1
+            ;;
+        *)
+            break
             ;;
     esac
+    shift
 done
-
-shift $((OPTIND-1))
 
 # shellcheck disable=SC1091
 . /usr/local/share/bash/puppet-common.sh
 
-if ! wait_for_puppet 3; then
-    echo "Waited 30 seconds and a preceding puppet run is still ongoing, aborting"
+test "$force" && puppet agent --enable
+test "$enable" && enable-puppet "$enable"
+
+if ! wait_for_puppet "$attempts"; then
+    SECONDS=$(( $attempts * 10 ))
+    echo "Waited ${SECONDS} seconds and a preceding puppet run is still ongoing, aborting"
     exit 1
 fi
 puppet agent --onetime --no-daemonize $verbose_opts --no-splay --show_diff \
