Check the return status of nextJobDB.php.
* This avoids passing exceptions as the name of a DB to runJobs.

Change-Id: Ia9724744b9382a75cd94827dbbbfa41bdd86e184

diff --git a/modules/mediawiki_new/templates/jobrunner/jobs-loop.sh.erb b/modules/mediawiki_new/templates/jobrunner/jobs-loop.sh.erb
--- a/modules/mediawiki_new/templates/jobrunner/jobs-loop.sh.erb
+++ b/modules/mediawiki_new/templates/jobrunner/jobs-loop.sh.erb
@@ -83,7 +83,10 @@ while [ 1 ];do
 		moreprio=
 		for type in $types; do
 			db=`php MWScript.php nextJobDB.php --wiki=aawiki --type="$type"`
-			if [ -n "$db" ]; then
+
+			if [ "$?" -ne "0" ]; then
+				echo "Could not determine the next wiki."
+			elif [ -n "$db" ]; then
 				echo "$db $type"
 				nice -n 20 php MWScript.php runJobs.php --wiki="$db" --procs=<%= procs %> --type="$type" --maxtime=$maxtime &
 				wait
@@ -96,7 +99,9 @@ while [ 1 ];do
 		# Do the remaining types
 		db=`php MWScript.php nextJobDB.php --wiki=aawiki`
 
-		if [ ! -z "$db" ];then
+		if [ "$?" -ne "0" ]; then
+			echo "Could not determine the next wiki."
+		elif [ ! -z "$db" ];then
 			echo "$db"
 			nice -n 20 php MWScript.php runJobs.php --wiki="$db" --procs=<%= procs %> --maxtime=$maxtime &
 			wait
