puppetmaster: adapt wmf-reimage to use remote salt calls
Since puppetmaster and saltmaster are not on the same machine anymore,
we cannot run salt-key locally anymore.

We use a salt runner to execute actions on the master, and get feedback
from our actions.

Bug: T124761
Change-Id: If62bb08f84670b4d290ef34fa8e191a92a8ed1ef

diff --git a/modules/puppetmaster/files/wmf-reimage b/modules/puppetmaster/files/wmf-reimage
--- a/modules/puppetmaster/files/wmf-reimage
+++ b/modules/puppetmaster/files/wmf-reimage
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Helper script for reimaging a server.
 # Author: Giuseppe Lavagetto
-# Copyright (c) 2014 the Wikimedia Foundation
+# Copyright (c) 2014-2016 the Wikimedia Foundation
 set -e
 set -u
 SLEEPTIME=60
@@ -27,24 +27,26 @@ function clean_puppet {
     /usr/local/sbin/puppetstoredconfigclean.rb ${nodename}
 }
 
+function __salt {
+    # Executes a salt key action via salt-call
+    local action=${1}
+    local nodename=${2}
+    salt-call --output=json publish.runner "keys.${action}" ${nodename} 2>/dev/null | jq --monochrome-output ".local.status"
+}
+
 function clean_salt {
     nodename=${1}
     force_yes=${2}
     log "cleaning salt key cache for ${nodename}"
     # delete the key only if it has been accepted already, we are going to
     # ask confirmation later about unaccepted keys
-    if salt-key --list accepted | fgrep -q ${nodename}; then
-        if [ ${force_yes} -eq 1 ]; then
-            salt-key -y --rotate-aes-key= --delete ${nodename}
-        else
-            salt-key --rotate-aes-key= --delete ${nodename}
+    if ( __salt status "${nodename}" ) | fgrep -q "accepted"; then
+        local retval=$( __salt delete ${nodename} )
+        if [ "x${retval}" != ''"done" ]; then
+            log "unable to clean salt key, please check manually"
+            log "Maybe you need to use the -n switch?"
+            exit 1
         fi
-    fi
-    # salt-key --delete above exits 0 regardless, double check
-    if salt-key --list accepted | fgrep -q ${nodename}; then
-        log "unable to clean salt key, please check manually"
-        log "Maybe you need to use the -n switch?"
-        exit 1
     fi
 }
 
@@ -84,18 +86,16 @@ function sign_salt {
     log "Seeking the SALT node key to add"
     log "This is the time to start a puppet run on the host."
     while true; do
-        if ! salt-key --list unaccepted | fgrep -q ${nodename}; then
+        if ( __salt status ${nodename} ) | fgrep -qv "accepted"; then
             echo -n "."
             sleep $SLEEPTIME
             continue
         fi;
-        echo "+"
-        if [ ${force_yes} -eq 1 ]; then
-            salt-key -y -a ${nodename}
-        else
-            salt-key -a ${nodename}
-        fi
-        break
+        local retval=$( __salt accept ${nodename} )
+        if [ "x${retval}" == 'x"done"' ]; then
+            echo "+"
+            break
+        fi;
     done
 }
 
