gitlab: add backup type failover to script output
In I30bc41d8dc7b793505697b80efacb3c4d857b8d2 backup type failover was
added to gitlab-backup.sh script. This change adds this type to the
echo command too.

Bug: T330771
Change-Id: Ie095a633f24383251d8e88f7e28b2da769f5c52b

diff --git a/modules/gitlab/templates/gitlab-backup.sh.erb b/modules/gitlab/templates/gitlab-backup.sh.erb
--- a/modules/gitlab/templates/gitlab-backup.sh.erb
+++ b/modules/gitlab/templates/gitlab-backup.sh.erb
@@ -32,5 +32,5 @@ case "$1" in
     # full backup for failover, including builds, artifacts and registry and without copy strategy
     /usr/bin/gitlab-backup create CRON=1 GZIP_RSYNCABLE="<%= @rsyncable_gzip %>" GITLAB_BACKUP_MAX_CONCURRENCY="<%= @max_concurrency %>" GITLAB_BACKUP_MAX_STORAGE_CONCURRENCY="<%= @max_storage_concurrency %>";;
     *)
-    echo "Please run script with parameter [full, partial, config]"; exit 1 ;;
+    echo "Please run script with parameter [full, partial, config, failover]"; exit 1 ;;
 esac
