cloudstore: remove dependency on bind mounts
Serve NFSv4 (only) without bind mounts, which block failover. This may correct
basically all the problems with our currently very vulnerable NFS servers.

This requires several changes to work smoothly.

Bug: T224582
Bug: T169570
Bug: T203469
Change-Id: I8fe9cbb84331c527cf3623a2204ceb835c604ff5

diff --git a/modules/profile/templates/wmcs/nfs/nfs-manage.sh.erb b/modules/profile/templates/wmcs/nfs/nfs-manage.sh.erb
--- a/modules/profile/templates/wmcs/nfs/nfs-manage.sh.erb
+++ b/modules/profile/templates/wmcs/nfs/nfs-manage.sh.erb
@@ -13,7 +13,7 @@
 # status - Display mount and drbd status
 
 # T169570
-echo "This cannot be run as a script currently"
+<%# echo "This cannot be run as a script currently"
 echo "These steps can be followed to handle failover manually..."
 echo "Except the 'down' process on the current primary fails at:"
 echo " /usr/local/sbin/nfs-manage-binds"
@@ -21,7 +21,7 @@ echo "A reboot taking the current primary offline and allowing the"
 echo "use of '/sbin/drbdadm primary all --force' on the secondary "
 echo "is the current terrible process in use."
 echo "T169570 and T157478 are the issues to address this."
-exit 1
+exit 1 %>
 
 CMD="$1"
 
@@ -53,16 +53,12 @@ case $CMD in
 
         /usr/sbin/drbd-overview
         /usr/bin/timeout 10s sudo -u nfsmanager nfs-exportd
-        /usr/local/sbin/nfs-manage-binds
-        /usr/sbin/service nfs-kernel-server start
+        <%= @nfs_start_command %>
         ;;
     down)
         echo "Taking down drbd and nfs"
         /usr/sbin/drbd-overview
-        /usr/sbin/service nfs-kernel-server stop
-
-        /usr/local/sbin/nfs-manage-binds -binds | \
-            xargs --no-run-if-empty /bin/umount -f
+        <%= @nfs_stop_command %>
 
         <% @drbd_resource_config.each do |resource, config| %>
         umount <%= config['device'] %> <%= config['mount_path'] -%>
@@ -74,7 +70,7 @@ case $CMD in
         ;;
     status)
         /usr/sbin/drbd-overview
-        showmount -e localhost | wc -l
+        # showmount -e localhost | wc -l
         ;;
     *)
         echo $"Usage: $0 {up|down|status}"
