check_wikitech_static - fix for monitoring
Add cases for failing to fetch the timestamps from
one of the 2 wikis in the first place so we can't end
up as OK even though wikitech-static couldn't even be reached.

Bug:T101803
Change-Id: I4e06451349bc1e2a390302fb4a1867ccdb9d6f0c

diff --git a/modules/icinga/files/check_wikitech_static b/modules/icinga/files/check_wikitech_static
--- a/modules/icinga/files/check_wikitech_static
+++ b/modules/icinga/files/check_wikitech_static
@@ -21,6 +21,19 @@ TS_DIFF=$(( $TS_WS - $TS_SS ))
 
 # echo "diff is ${TS_DIFF}"
 
+if [ -z $TS_WIKITECH ]; then
+
+    echo "wikitech-static CRIT - failed to fetch timestamp from wikitech"
+    exit 2
+fi
+
+
+if [ -z $TS_STATIC ]; then
+
+    echo "wikitech-static CRIT - failed to fetch timestamp from wikitech-static"
+    exit 2
+fi
+
 if [ $TS_DIFF -gt $AGE_LIMIT ]; then
 
     echo "wikitech-static CRIT - wikitech and wikitech-static out of sync (${TS_DIFF}s > ${AGE_LIMIT}s)"
