Switch gdnsd config-geo mechanism to $include
*) The primary config in puppet is now "config", not "config-head"
*) "config" has "$include{config-geo}" at the bottom
*) config updates in puppet now send notify for gdnsd restart
*) The authdns-local-update script now does the
   "backup -> install -> check -> revert?" on just the config-geo
   file, without touching "config"

Change-Id: Ib0853afc8b29729ae8cdd185716d889c9e745554

diff --git a/modules/authdns/files/authdns-local-update b/modules/authdns/files/authdns-local-update
--- a/modules/authdns/files/authdns-local-update
+++ b/modules/authdns/files/authdns-local-update
@@ -66,8 +66,8 @@ fi
 echo "Pulling the current revision from $REMOTE"
 (cd $WORKINGDIR; sudo -u authdns authdns-git-pull $PULL_ARGS $REMOTE)
 
-if [ ! -e "/etc/gdnsd/config-head" ]; then
-    die "config-head not found, system misconfigured?"
+if [ ! -e "/etc/gdnsd/config" ]; then
+    die "config not found, system misconfigured?"
 fi
 if [ ! -e "$WORKINGDIR/templates" ]; then
     die "templates not found, system misconfigured?"
@@ -79,39 +79,36 @@ fi
 echo "Generating zonefiles from zone templates"
 authdns-gen-zones $WORKINGDIR/templates /etc/gdnsd/zones
 
-echo "Generating gdnsd config"
-cp -f $WORKINGDIR/config-geo /etc/gdnsd/
-cp -f /etc/gdnsd/config /etc/gdnsd/config~ 2>/dev/null || true
-cat /etc/gdnsd/config-head /etc/gdnsd/config-geo > /etc/gdnsd/config
-
 echo "Doing sanity checks"
-if [ ! -s "/etc/gdnsd/config" ]; then
-    die "config seems empty, aborting"
-elif [ `ls /etc/gdnsd/zones |wc -l` -le 10 ]; then
+if [ `ls /etc/gdnsd/zones |wc -l` -le 10 ]; then
     die "less than 10 zones, something's probably wrong, aborting";
 fi
 
+echo "Copy config-geo"
+cp -f /etc/gdnsd/config-geo /etc/gdnsd/config-geo~ 2>/dev/null || true
+cp -f $WORKINGDIR/config-geo /etc/gdnsd/
+
 # initial run, before gdnsd was installed
 if ! which gdnsd > /dev/null || [ "$SKIP_RELOAD" = "true" ]; then
-    rm -f /etc/gdnsd/config~
+    rm -f /etc/gdnsd/config-geo~
     exit 0
 fi
 
 if ! gdnsd checkconf >/dev/null; then
-    if [ -f /etc/gdnsd/config~ ]; then
-        mv /etc/gdnsd/config~ /etc/gdnsd/config
+    if [ -f /etc/gdnsd/config-geo~ ]; then
+        mv /etc/gdnsd/config-geo~ /etc/gdnsd/config-geo
     fi
     die "gdnsd checkconf failed, aborting"
 fi
 
 ### reload
 
-if ! cmp --quiet /etc/gdnsd/config~ /etc/gdnsd/config; then
-    rm -f /etc/gdnsd/config~
+if ! cmp --quiet /etc/gdnsd/config-geo~ /etc/gdnsd/config-geo; then
+    rm -f /etc/gdnsd/config-geo~
     echo "Restarting to update zones & config"
     gdnsd restart
 else
-    rm -f /etc/gdnsd/config~
+    rm -f /etc/gdnsd/config-geo~
     echo "Reloading zones"
     gdnsd reload-zones
 fi
