jessie-backports: warn users if they try to use backports on jessie
Also add's a new variable ARCHIVE so user can attempt to use
archive.debian.org

Host: boron.eqiad.wmnet

Bug: T219333
Change-Id: I63829200bb444163c8710788ae0ac4c6afd3f623

diff --git a/modules/package_builder/templates/D02backports.erb b/modules/package_builder/templates/D02backports.erb
--- a/modules/package_builder/templates/D02backports.erb
+++ b/modules/package_builder/templates/D02backports.erb
@@ -1,7 +1,15 @@
 #!/bin/sh
-
 # Avoid running hooks if backports is not specified
 if [ "${BACKPORTS}" = "yes" ]; then
+<%- if @distribution == 'jessie' -%>
+        printf '\033[0;31m'
+        printf 'ERROR: jessie no longer support backports. packages should ideally be rebuilt with\n'
+        printf 'ERROR: internally built components. If this isn't possible for some reason, the\n'
+        printf 'ERROR: ARCHIVE_BACKPORTS hook can be used to pull in the backports repository from\n'
+        printf 'ERROR: archive.debian.org\n'
+        printf '\033[0m\n'
+		exit 1
+<%- elsif @distribution == 'stretch' -%>
 	cat > /etc/apt/sources.list.d/<%= @distribution %>-backports.list <<-'EOF'
 	deb <%= @upstream_mirror %> <%= @distribution %>-backports main contrib non-free
 	deb-src <%= @upstream_mirror %> <%= @distribution %>-backports main contrib non-free
@@ -12,4 +20,7 @@ EOF
 	Pin-Priority: 500
 EOF
 	apt-get update
+<%- else -%>
+	printf '\033[0;31m ERROR: <%= @distribution %> does not have backports \033[0m\n'
+<%- end -%>
 fi
