optionally analayze all queries to a server via tcpdump for a limited time
Change-Id: Icc28bc4f9edd421875e9ce458fe4fb608115b365

diff --git a/templates/mysql/send_query_digest.sh.erb b/templates/mysql/send_query_digest.sh.erb
--- a/templates/mysql/send_query_digest.sh.erb
+++ b/templates/mysql/send_query_digest.sh.erb
@@ -10,24 +10,30 @@ digest_host=<%= digest_host %>
 digest_db=<%= digest_db %>
 hostname=$(hostname)
 log=/a/sqldata/${hostname}-slow.log
+runtime=8m
 
-# exit quietly if $log does not exist or is 0 bytes
-[ -s $log ] || exit 0
+digestif() {
+	/usr/bin/pt-query-digest --review h=${digest_host},D=${digest_db},t=${hostname}_query_review,u=${mysql_user},p=${pw} \
+		--create-review-table \
+		--review-history h=${digest_host},D=${digest_db},t=${hostname}_query_review_history,u=${mysql_user},p=${pw} \
+		--create-review-history-table \
+		--noreport \
+		--run-time $runtime \
+		--filter '$event->{fingerprint} !~ m/^select master_pos_wait/' \
+		$log
+}
 
-# kill any running pt-query-digest procs
-# this is paranoia over a potential pileup in the case
-# of very large log files as was previously observed 
-# with mk-query-digest. shouldn't be needed due to
-# --run-time parameter
-/usr/bin/pgrep -f /usr/bin/pt-query-digest >/dev/null && /usr/bin/pkill -9 -f /usr/bin/pt-query-digest
-
-/usr/bin/pt-query-digest --review h=${digest_host},D=${digest_db},t=${hostname}_query_review,u=${mysql_user},p=${pw} \
-	--create-review-table \
-	--review-history h=${digest_host},D=${digest_db},t=${hostname}_query_review_history,u=${mysql_user},p=${pw} \
-	--create-review-history-table \
-	--noreport \
-	--run-time 9m \
-	--filter '$event->{fingerprint} !~ m/^select master_pos_wait/' \
-	$log
-
-> $log
+# optionally analayze all query traffic via tcpdump for a limited time
+if [ "$1" = "tcpdump" ] ; then
+	# safeguard in case of --run-time failure
+	/usr/bin/pgrep -f "pt-query-digest.*tcpdump" >/dev/null && /usr/bin/pkill -f "pt-query-digest.*tcpdump"
+	log="--type tcpdump --limit 100"
+	runtime=30s
+	tcpdump -s 65535 -x -nn -q -tttt -i any port 3306 | digestif
+else
+	[ -s $log ] || exit 0
+	# safeguard in case of --run-time failure
+	/usr/bin/pgrep -f "pt-query-digest.*${log}" >/dev/null && /usr/bin/pkill -9 -f "pt-query-digest.*${log}"
+	digestif
+	> $log
+fi
