Add a --verbose parameter to mw-update-l10n
To supersede I5f95f7af

Change-Id: Ic6db1d8a5304257999cf9a09c4e0d5c08ba51a20

diff --git a/files/scap/mw-update-l10n b/files/scap/mw-update-l10n
--- a/files/scap/mw-update-l10n
+++ b/files/scap/mw-update-l10n
@@ -11,6 +11,29 @@ BINDIR=/usr/local/bin
 SOURCE=/home/wikipedia/common
 DEST=/usr/local/apache/common-local
 
+if [ "`uname -s`" != Linux ]; then
+	echo "ERROR: This script requires the Linux operating system to function correctly"
+	exit 1
+fi
+
+QUIET=--quiet
+TEMP=`getopt -o '' -l verbose -- "$@"`
+if [ $? -ne 0 ]; then
+	exit 1
+fi
+eval set -- "$TEMP"
+while true; do
+	case "$1" in
+		--verbose)
+			QUIET=
+			shift
+			;;
+		--)
+			shift
+			break
+	esac
+done
+
 mwExtVerDbSets=$($BINDIR/mwversionsinuse --extended --withdb)
 # Regenerate the extension message file list for all active MediaWiki versions
 for i in ${mwExtVerDbSets[@]}; do
@@ -18,7 +41,7 @@ for i in ${mwExtVerDbSets[@]}; do
 	mwDbName=${i#*=}
 	echo "Updating ExtensionMessages-$mwVerNum.php..."
 	sudo -u apache $BINDIR/mwscript mergeMessageFileList.php --wiki="$mwDbName" \
-		--list-file=$SOURCE/wmf-config/extension-list \
+		--list-file=$SOURCE/wmf-config/extension-list $QUIET \
 		> $SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php
 
 	# Update ExtensionMessages-*.php in the local copy
@@ -26,7 +49,7 @@ for i in ${mwExtVerDbSets[@]}; do
 
 	echo -n "Updating LocalisationCache for $mwVerNum... "
 	sudo -u l10nupdate $BINDIR/mwscript rebuildLocalisationCache.php --wiki="$mwDbName" \
-		--quiet --outdir=$SOURCE/php-$mwVerNum/cache/l10n
+		--outdir=$SOURCE/php-$mwVerNum/cache/l10n $QUIET
 	echo "done"
 done
 
