Re-set common rsync and dsh parameters in mw-deployment-vars
This was first implemented in I702777b4a, but that change contained a bug and
had to be reverted (change I4e6675efe). The bug was that 'mwversioninuse' used
/bin/sh as the interpreter, which means it could not source
mw-deployment-vars.sh, as the latter file uses Bash arrays, which are not POSIX
compliant.

Change-Id: I2800d01a6b29a323c33a4feeb44c55d60a612736

diff --git a/files/scap/scap-1 b/files/scap/scap-1
--- a/files/scap/scap-1
+++ b/files/scap/scap-1
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-if [ ! -d /usr/local/apache/common-local ];then
-	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/common-local; then
-		echo "Unable to create common-local, please re-run this script as root."
+. /usr/local/lib/mw-deployment-vars.sh
+
+if [ ! -d "${MW_COMMON}" ];then
+	if ! install -d -o mwdeploy -g mwdeploy "${MW_COMMON}"; then
+		echo "Unable to create ${MW_COMMON}, please re-run this script as root."
 		exit 1
 	fi
 fi
@@ -20,7 +22,7 @@ if [ -n "$RSYNC_SERVERS" ]; then
 	SERVER=$(sudo /usr/local/bin/find-nearest-rsync $RSYNC_SERVERS)
 fi
 if [ -z "$SERVER" ]; then
-	SERVER=tin.eqiad.wmnet
+	SERVER="${MW_RSYNC_HOST}"
 fi
 
 sudo -u mwdeploy /usr/local/bin/scap-2 "$SERVER"
