Revert "Set common rsync and dsh parameters in mw-deployment-vars"
/usr/local/bin/mwversionsinuse: 7: /usr/local/lib/mw-deployment-vars.sh: Syntax error: "(" unexpected
Unable to read wikiversions.dat or it is empty.

This reverts commit 7eba91549ad226a4f939ed7144ecf88f1900ffb1.

Change-Id: I4e6675efe28d89e52453b0e2d494881e82cef005

diff --git a/files/scap/scap-1 b/files/scap/scap-1
--- a/files/scap/scap-1
+++ b/files/scap/scap-1
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-. /usr/local/lib/mw-deployment-vars.sh
-
-if [ ! -d "${MW_COMMON}" ];then
-	if ! install -d -o mwdeploy -g mwdeploy "${MW_COMMON}"; then
-		echo "Unable to create ${MW_COMMON}, please re-run this script as root."
+if [ ! -d /usr/local/apache/common-local ];then
+	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/common-local; then
+		echo "Unable to create common-local, please re-run this script as root."
 		exit 1
 	fi
 fi
@@ -22,7 +20,7 @@ if [ -n "$RSYNC_SERVERS" ]; then
 	SERVER=$(sudo /usr/local/bin/find-nearest-rsync $RSYNC_SERVERS)
 fi
 if [ -z "$SERVER" ]; then
-	SERVER="${MW_RSYNC_HOST}"
+	SERVER=tin.eqiad.wmnet
 fi
 
 sudo -u mwdeploy /usr/local/bin/scap-2 "$SERVER"
