(ori) dotfiles update
Change-Id: If471497e049824f6a60081ebacc046a9a4da9b8d

diff --git a/modules/admin/files/home/ori/.binned/disable-puppet b/modules/admin/files/home/ori/.binned/disable-puppet
--- a/modules/admin/files/home/ori/.binned/disable-puppet
+++ b/modules/admin/files/home/ori/.binned/disable-puppet
@@ -45,8 +45,11 @@ case "$1" in
     ;;
 esac
 
-test -f /var/lib/puppet/state/agent_disabled.lock && {
-  echo >&2 "puppet agent is already disabled!"
+LOCK_FILE="/var/lib/puppet/state/agent_disabled.lock"
+
+/usr/bin/sudo test -f "$LOCK_FILE" && {
+  REASON="$(/usr/bin/sudo /usr/bin/cut -d'"' -f4 "$LOCK_FILE")"
+  echo >&2 "Error: Puppet is already disabled: \"${REASON}\"."
   exit 1
 }
 
@@ -55,4 +58,4 @@ DURATION="${DURATION:-1h}"
 REASON="${*:-Disabled by ${USER} for ${DURATION} at ${TIMESTAMP}}"
 echo "Disabling Puppet for ${DURATION} with reason: \"${REASON}\"."
 /usr/bin/sudo /usr/bin/puppet agent --verbose --disable "$REASON"
-/usr/bin/screen -d -m /usr/bin/sudo -n /bin/bash -c "/bin/sleep $DURATION ; /usr/bin/puppet agent --enable"
+( { /bin/sleep "$DURATION" ; sudo /usr/bin/puppet agent --enable ; } >/dev/null 2>&1 &)
