icinga: sync only if config is valid and log it
* Given that the sync script to replicate the current state from the
  active host to the passive host needs to stop Icinga and given that
  Icinga would not restart if the configuration is not valid, bail out
  the synchronization process in case of invalid Icinga configuration.
* Add logging to the crontab of the sync via systemd-cat to be able to
  troubleshoot any issue.

Change-Id: Ie7029181761842f0feb3bf0d51348e8d836ff580

diff --git a/modules/role/templates/icinga/sync_icinga_state.sh.erb b/modules/role/templates/icinga/sync_icinga_state.sh.erb
--- a/modules/role/templates/icinga/sync_icinga_state.sh.erb
+++ b/modules/role/templates/icinga/sync_icinga_state.sh.erb
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+# Bail out if Icinga configuration is not valid, it would not restart
+if ! /usr/sbin/icinga -v /etc/icinga/icinga.cfg > /dev/null 2>&1; then
+    echo "Icinga configuration contains errors, skipping sync"
+    exit 1
+fi
+
 # Stop the service first to avoid inconsistencies
 /usr/sbin/service icinga stop
 /usr/bin/rsync -a rsync://<%= @active_host %>/icinga-tmpfs/status.dat /var/icinga-tmpfs/status.dat
