amd-gpu: handle service deadlock
Why:
Due to unit dependencies the restart of the
device plugin would not suceede

Hosts: auto
Change-Id: I1fd2d491588c9f608c7cda16cff911ef1886d632

diff --git a/modules/profile/templates/amd_gpu/amd-smi-gpu-partition.sh.erb b/modules/profile/templates/amd_gpu/amd-smi-gpu-partition.sh.erb
--- a/modules/profile/templates/amd_gpu/amd-smi-gpu-partition.sh.erb
+++ b/modules/profile/templates/amd_gpu/amd-smi-gpu-partition.sh.erb
@@ -16,9 +16,9 @@ restart_if_active() {
     local service="$1"
 
     if systemctl is-active --quiet "${service}"; then
-        log "Restarting ${service}"
-        systemctl restart "${service}" || {
-            log "ERROR: Failed to restart ${service}"
+        log "Queueing restart for ${service}"
+        systemctl --no-block try-restart "${service}" || {
+            log "ERROR: Failed to queue restart for ${service}"
             exit 1
         }
     else
